# Enable Gradle configuration cache if you'd like:
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219

mod_id=autonomousvillagers
mod_name=Autonomous Villagers
mod_license=GPL-3.0-or-later
mod_version=1.0.0
mod_group_id=de.petrofsky.autonomousvillagers
mod_authors=Robin Petrofsky
mod_description=A mod that makes villagers farm and store resources autonomously.