package de.petrofsky.autonomousvillagers.mixin;

import net.minecraft.core.Holder;
import net.minecraft.world.entity.ai.village.poi.PoiType;
import net.minecraft.world.entity.ai.village.poi.PoiTypes;
import net.minecraft.world.level.block.state.BlockState;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.Set;

@Mixin(PoiTypes.class)
public class PoiTypesMixin {

    /** Uses mixins to remove the composter as poi block for the vanilla farmer to use it for the modded farmer.
     * The advantage is that the composter block is by default generated by vanilla minecraft or usually by mods that
     * change the generation of villages, so I don't have to implement some custom generation logic.
     *
     * @param type The Point of Interest (POI) type currently being registered (e.g., PoiTypes.FARMER).
     * @param states The set of block states being assigned to this POI
     * (e.g., all different fill-level variants in the case of the composter).
     * @param ci The Mixin CallbackInfo object, used to control the execution flow
     * of the original method and, in this case, to cancel it prematurely.
     */
    @Inject(method = "registerBlockStates", at = @At("HEAD"), cancellable = true)
    private static void removeComposter(Holder<PoiType> type, Set<BlockState> states, CallbackInfo ci) {
        // Checks whether the poi type belongs to the vanilla farmer
        if (type.is(PoiTypes.FARMER)) {
            // Cancels the registration of the composter block for the vanilla farmer
            ci.cancel();
        }
    }
}
